# Generated by Django 2.2.10 on 2020-11-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=40)),
                ('massage', models.CharField(max_length=150)),
                ('subjuct', models.CharField(max_length=150)),
            ],
        ),
    ]
