# Generated by Django 2.2.10 on 2020-11-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='contract',
        ),
    ]
