# Generated by Django 2.2.13 on 2020-11-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_auto_20201109_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(default=models.CharField(max_length=150), max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('available', models.BooleanField()),
                ('details', models.TextField()),
                ('category', models.CharField(choices=[('T', 'T'), ('S', 'S')], max_length=50)),
            ],
        ),
    ]
