# Generated by Django 2.2.13 on 2020-11-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', height_field='100px', upload_to='media/images', width_field='100px'),
        ),
    ]
