# Generated by Django 2.2.13 on 2020-11-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0009_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='tuition/images'),
        ),
    ]
