# Generated by Django 2.2.13 on 2020-11-23 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tuition', '0013_auto_20201115_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='postviewtemp',
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
