# Generated by Django 2.2.13 on 2020-11-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0014_auto_20201124_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'class_in',
                'verbose_name_plural': 'class_ins',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='class_in',
            field=models.ManyToManyField(related_name='class_set', to='tuition.Class_in'),
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.ManyToManyField(related_name='subject_set', to='tuition.Student'),
        ),
    ]
