# Generated by Django 2.2.13 on 2020-11-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0015_auto_20201128_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class_in',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
