# Generated by Django 2.2.13 on 2020-11-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0017_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
