# Generated by Django 2.2.13 on 2020-11-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0018_delete_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Subject',
        ),
    ]
